<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-7Q4V18QD" failures="2" tests="12" name="parametertest" time="0.163" errors="0" timestamp="2022-05-24T14:37:18 IST">
  <testcase classname="RetrylogictestNG.Rtrylogictestcase" name="test1" time="0.013">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="RetrylogictestNG.Rtrylogictestcase" name="test1" time="0.001">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="RetrylogictestNG.Rtrylogictestcase" name="test1" time="0.001">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="RetrylogictestNG.Rtrylogictestcase" name="test1" time="0.002">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="RetrylogictestNG.Rtrylogictestcase" name="test1" time="0.002">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="RetrylogictestNG.Rtrylogictestcase" name="test1" time="0.004">
    <failure type="java.lang.AssertionError" message="expected [true] but found [flse]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [flse]
at RetrylogictestNG.Rtrylogictestcase.test1(Rtrylogictestcase.java:10)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="RetrylogictestNG.Rtrylogictestcase" name="test2" time="0.001">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="RetrylogictestNG.Rtrylogictestcase" name="test2" time="0.003">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="RetrylogictestNG.Rtrylogictestcase" name="test2" time="0.002">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="RetrylogictestNG.Rtrylogictestcase" name="test2" time="0.002">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="RetrylogictestNG.Rtrylogictestcase" name="test2" time="0.002">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="RetrylogictestNG.Rtrylogictestcase" name="test2" time="0.011">
    <failure type="java.lang.AssertionError" message="expected [sary] but found [selse]">
      <![CDATA[java.lang.AssertionError: expected [sary] but found [selse]
at RetrylogictestNG.Rtrylogictestcase.test2(Rtrylogictestcase.java:14)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
</testsuite> <!-- parametertest -->
